const products = [
  {
    id: 1,
    photo: 'asus_tuf_gaming_27.jpg',
    title: 'Asus TUF Gaming VG27AQ1A',
    type: 'Monitor',
    brand: 'ASUS',
    series: 'TUF',
    productType: 'gaming monitor',
    price: 380,
    date: 'February, 2021',
    description: `
     Despite the fact that products from the TUF series belong more to the middle class, this model is an
     excellent example of a universal gaming monitor that fully complies with all the fashion trends of recent years,
     and practically does not lag behind Asus ROG hi-end monitors in terms of its functionality. The massive 27-inch
     Asus TUF Gaming VG27AQ1A monitor is built on a high-end 10-bit IPS matrix with a resolution of 2560x1440 pixels,
     features reference color reproduction and simultaneous AMD FreeSync Premium and NVIDIA G-Sync Compatible
     certification.`,
    technicalDetails: {
      screen: {
        displaySize: 27,
        panelType: 'IPS',
        surfaceTreatment: 'glossy (anti-reflective)',
        resolution: '2560x1440 (16:9)',
        responsiveTime: '1 ms',
        refreshRate: '170 Hz',
        brightness: '250 cd/m2',
        contrast: '1 000:1',
        colourDepth: '8 bit',
        colourSpace: '96 %',
        hdr: true,
      },
      connectors: {
        connections: ['DisplayPort v1.2'],
        hdmi: 2,
        hdmiVersion: 2,
        connectors: 'mini-Jack output (3.5 mm)',
      },
      features: {
        features: ['Flicker-Free', 'AMD FreeSync Premium', 'NVIDIA G-Sync Compatible'],
        portraitPivot: false,
        screenRotation: false,
        heightAdjustment: false,
        speakers: true,
        soundPower: '4W / 2x2W',
        gameFeatures: ['aim', 'timer', 'FPS display', 'brighten darker areas', '/ Shadow Boost /'],
      },
      general: {
        slimBezel: true,
        wallMount: 'VESA 100x100mm',
        powerConsumption: '35 W',
        energyClass: 'F',
        externalPowerSupply: true,
        dimensions: '615x455x214 mm',
        weight: '5.4 kg',
        addToCatalog: '02/2021',
        code: '4718017784047',
      },
    },
  },
  {
    id: 2,
    photo: 'asus_tuf_gaming_24.jpg',
    title: 'Asus TUF Gaming VG249Q',
    type: 'Monitor',
    brand: 'ASUS',
    series: 'TUF',
    productType: 'gaming monitor',
    price: 235,
    date: 'January, 2020',
    description: `
     Full HD monitor from the gaming guard, armed with a 24-inch IPS panel with a frame rate of 144 Hz and a 
     response time of 1 ms. Also, in the list of advantages of the screen, it is necessary to write adaptive frame rate 
     synchronization AMD FreeSync, due to which it is possible to avoid image tearing and dropping frames when 
     transmitting a signal from the source to the monitor, ELMB Sync (Extreme Low Motion Blur Sync) technology, which 
     allows you to reduce motion blur , and Flicker-Free backlight flicker minimization.`,
    technicalDetails: {
      screen: {
        displaySize: 24,
        panelType: 'IPS',
        surfaceTreatment: 'glossy (anti-reflective)',
        resolution: '1920x1080 (16:9)',
        responsiveTime: '1 ms',
        refreshRate: '144 Hz',
        brightness: '250 cd/m2',
        contrast: '1 000:1',
        colourDepth: '6 bit + FRC',
        colourSpace: '72 %',
        hdr: true,
      },
      connectors: {
        connections: ['DisplayPort v1.2', 'VGA'],
        hdmi: 2,
        hdmiVersion: 2,
        connectors: 'mini-Jack output (3.5 mm)',
      },
      features: {
        features: ['Flicker-Free', 'AMD FreeSync'],
        portraitPivot: true,
        screenRotation: true,
        heightAdjustment: true,
        speakers: true,
        soundPower: '4W / 2x2W',
        gameFeatures: ['aim', 'timer', 'FPS display', 'brighten darker areas', '/ Shadow Boost /'],
      },
      general: {
        slimBezel: true,
        wallMount: 'VESA 100x100mm',
        powerConsumption: '16 W',
        energyClass: '',
        externalPowerSupply: '',
        dimensions: '541x515x218 mm',
        weight: '6.5 kg',
        addToCatalog: '01/2020',
        code: '4718017485395',
      },
    },
  },
  {
    id: 3,
    photo: 'asus_pro_art_27.jpg',
    title: 'Asus ProArt PA279CV',
    type: 'Monitor',
    brand: 'ASUS',
    series: 'ProArt',
    productType: 'for graphics',
    price: 515,
    date: 'February, 2021',
    description: `
     High-quality 27" monitor with detailed 4K resolution, enhanced colour gamut, full support for high dynamic range 
     (HDR10) images and built-in stereo speakers (2x2W). In addition to ultra-high resolution (3840x2160), it has good 
     colour reproduction and high-quality factory calibration, which allows it to be used for professional work with 
     raster and vector images. It is positioned as a multi-purpose monitor for graphic workstations.`,
    technicalDetails: {
      screen: {
        displaySize: 27,
        panelType: 'IPS',
        surfaceTreatment: 'glossy (anti-reflective)',
        resolution: '3840x2160 (16:9)',
        responsiveTime: '5 ms',
        refreshRate: '60 Hz',
        brightness: '350 cd/m2',
        contrast: '1 000:1',
        colourDepth: '8 bit + FRC',
        colourSpace: '100 %',
        hdr: true,
      },
      connectors: {
        connections: ['DisplayPort v1.2', 'USB C (DisplayPort Alt Mode)'],
        hdmi: 2,
        hdmiVersion: 2,
        connectors: 'mini-Jack output (3.5 mm)',
      },
      features: {
        features: ['Flicker-Free', 'CalMAN certification'],
        portraitPivot: true,
        screenRotation: true,
        heightAdjustment: true,
        speakers: true,
        soundPower: '4W / 2x2W',
        gameFeatures: ['aim', 'timer', 'FPS display', 'brighten darker areas', '/ Shadow Boost /'],
      },
      general: {
        slimBezel: true,
        wallMount: 'VESA 100x100mm',
        powerConsumption: '16 W',
        energyClass: '',
        externalPowerSupply: '',
        dimensions: '614x524x228 mm',
        weight: '8.6 kg',
        addToCatalog: '02/2021',
        code: '4718017853200',
      },
    },
  },
  {
    id: 4,
    photo: 'benq_mobiuz_25.jpg',
    title: 'BenQ Mobiuz EX2510S',
    type: 'Monitor',
    brand: 'BenQ',
    series: 'Mobiuz',
    productType: 'gaming monitor',
    price: 270,
    date: 'December, 2021',
    description: `
     Solid gaming monitor with a 24.5-inch FullHD-resolution screen and a semi-gloss anti-glare coating, an original 
     exterior design, a high refresh rate of 165 Hz, a multifunctional full-rotation stand and stereo speakers 
     (2x2.5 W). Supports high dynamic range (HDR) image output. It is also worth noting the proprietary Cinema HDRi 
     technology, which automatically optimizes contrast and colour reproduction, taking into account the readings of 
     the built-in light sensor and the nature of the displayed image.`,
    technicalDetails: {
      screen: {
        displaySize: 25,
        panelType: 'IPS',
        surfaceTreatment: 'glossy (anti-reflective)',
        resolution: '1920x1080 (16:9)',
        responsiveTime: '2 ms',
        refreshRate: '165 Hz',
        brightness: '400 cd/m2',
        contrast: '1 000:1',
        colourDepth: '8 bit',
        colourSpace: '99 %',
        hdr: true,
      },
      connectors: {
        connections: ['DisplayPort v1.2'],
        hdmi: 2,
        hdmiVersion: 2,
        connectors: 'mini-Jack output (3.5 mm)',
      },
      features: {
        features: ['Flicker-Free', 'AMD FreeSync Premium'],
        portraitPivot: false,
        screenRotation: true,
        heightAdjustment: true,
        speakers: true,
        soundPower: '5W / 2x2.5W',
        gameFeatures: ['brighten darker areas', '/ Black eQualizer /'],
      },
      general: {
        slimBezel: true,
        wallMount: 'VESA 100x100mm',
        powerConsumption: '18 W',
        energyClass: '',
        externalPowerSupply: '',
        dimensions: '557x522x217 mm',
        weight: '6.2 kg',
        addToCatalog: '12/2021',
        code: '0840046045562',
      },
    },
  },
  {
    id: 5,
    photo: 'benq_pd_25.jpg',
    title: 'BenQ PD2506Q',
    type: 'Monitor',
    brand: 'BenQ',
    series: 'PD',
    productType: 'for graphics',
    price: 400,
    date: 'November, 2022',
    description: `
     Made for Designers: 25 Inch DesignVue 2K QHD 60Hz IPS computer monitor is factory calibrated for color accuracy 
     and comes with a report straight from the manufacturer! Built with M-Book mode which features Mac compatible color
     matching. Experience Excellent Color Coverage: 95% P3 Display, 100% sRGB and average Delta E ≤3 for color 
     accuracy. CalMan verified and Pantone Validated.`,
    technicalDetails: {
      screen: {
        displaySize: 25,
        panelType: 'IPS',
        surfaceTreatment: 'glossy (anti-reflective)',
        resolution: '2560x1440 (16:9)',
        responsiveTime: '5 ms',
        refreshRate: '60 Hz',
        brightness: '350 cd/m2',
        contrast: '1 000:1',
        colourDepth: '8 bit',
        colourSpace: '95 %',
        hdr: true,
      },
      connectors: {
        connections: ['DisplayPort v 1.4', 'USB C (DisplayPort Alt Mode)', 'Thunderbolt'],
        hdmi: 1,
        hdmiVersion: 2,
        connectors: 'mini-Jack output (3.5 mm)',
      },
      features: {
        features: ['Flicker-Free', 'CalMAN certification', 'Pantone certification'],
        portraitPivot: true,
        screenRotation: true,
        heightAdjustment: true,
        speakers: true,
        soundPower: '5W',
        gameFeatures: '',
      },
      general: {
        slimBezel: true,
        wallMount: 'VESA 100x100mm',
        powerConsumption: '27 W',
        energyClass: 'G',
        externalPowerSupply: '',
        dimensions: '570х550х257 mm',
        weight: '7.6 kg',
        addToCatalog: '11/2022',
        code: '4718755089732',
      },
    },
  },
  {
    id: 6,
    photo: 'benq_zowie_27.jpg',
    title: 'BenQ Zowie XL2746K',
    type: 'Monitor',
    brand: 'BenQ',
    series: 'Zowie',
    productType: 'gaming monitor',
    price: 550,
    date: 'November, 2022',
    description: `
     The 27-inch gaming monitor has replenished BenQ's Zowie profile line in 2022. The model is positioned as a
     solution for cybersportsmen and represents the middle price segment. The characteristic gaming features include 
     protective sidewalls. They will not allow opponents who are nearby to spy on you. Also included in the package 
     is a special 5-position S-Switch: it will help you quickly adjust various image parameters, control gaming options 
     such as Black eQualizer (highlighting dark scenes).`,
    technicalDetails: {
      screen: {
        displaySize: 27,
        panelType: 'TN+film',
        surfaceTreatment: 'matte',
        resolution: '1920x1080 (16:9)',
        responsiveTime: '1 ms',
        refreshRate: '240 Hz',
        brightness: '320 cd/m2',
        contrast: '1 000:1',
        colourDepth: '6 bit + FRC',
        colourSpace: '72 %',
        hdr: false,
      },
      connectors: {
        connections: ['DisplayPort v 1.4', 'USB C (DisplayPort Alt Mode)', 'Thunderbolt'],
        hdmi: 3,
        hdmiVersion: 2,
        connectors: 'mini-Jack output (3.5 mm)',
      },
      features: {
        features: ['Flicker-Free'],
        portraitPivot: true,
        screenRotation: true,
        heightAdjustment: true,
        speakers: false,
        soundPower: '',
        gameFeatures: ['brighten darker areas', '/ Black eQualizer /', 'DyAc⁺'],
      },
      general: {
        slimBezel: false,
        wallMount: 'VESA 100x100mm',
        powerConsumption: '40 W',
        energyClass: 'F',
        externalPowerSupply: '',
        dimensions: '629x562x218 mm ',
        weight: '8.8 kg',
        addToCatalog: '11/2022',
        code: '4718755086687',
      },
    },
  },
];

module.exports = { products };
